### PR TITLE
Fix for hot reloading assets on Bevy 0.9

### LINKED ISSUE #22: Hot reload needs updated for Bevy 0.9
Currently running `cargo bavy new` and selecting hot reloading produces:
```rust
use bevy::asset::AssetServerSettings;
use bevy::prelude::*;

fn main() {
    App::new()
        // Enable hot reloading
        .insert_resource(AssetServerSettings {
            watch_for_changes: true,
            ..default()
        })
        .add_plugins(DefaultPlugins)
        .run();
}
```
Running this produces the following error:
```
unresolved import `bevy::asset::AssetServerSettings`                                                                                                                                
 --> src\main.rs:1:5
  |
1 | use bevy::asset::AssetServerSettings;
  |     ^^^^^^^^^^^^^-------------------
  |     |            |
  |     |            help: a similar name exists in the module: `AssetServerInternal`
  |     no `AssetServerSettings` in `asset`

```

For Bevy 0.9 it should be
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        // Enable hot reloading
        .add_plugins(DefaultPlugins.set(AssetPlugin {
            watch_for_changes: true,
            ..Default::default()
        }))
        .run();
}
```
Related section of the migration guide: https://bevyengine.org/learn/book/migration-guides/0.8-0.9/#plugins-own-their-settings-rework-plugingroup-trait
PR where this change was introduced: https://github.com/bevyengine/bevy/pull/6336

### PR DESCRIPTION
**Pull request by paul-hansen**
Fixes #22

Lmk if you would like anything done differently, or feel free to use this as a starting point etc.

### CODE REVIEW

File: src/new/mod.rs [hunk 1]
```diff
@@ -98,37 +98,34 @@ fn add_dependencies(context: &mut Context) {
...
-        imports.push("use bevy::asset::AssetServerSettings;");
-
         builder_methods.push(
             "// Enable hot reloading
-            .insert_resource(AssetServerSettings {
+            .add_plugins(DefaultPlugins.set(AssetPlugin {
                 watch_for_changes: true,
-                ..default()
-            })",
+                ..Default::default()
```
Comment (TimJentzsch) [inline src/new/mod.rs]: Why was this changed, does `..default()` not work anymore?

Comment (paul-hansen) [reply src/new/mod.rs]: Purely an accidental change. I copied the code from https://bevy-cheatbook.github.io/assets/hot-reload.html and didn't notice they used `Default::default()`. Changed it back.

**Review by TimJentzsch — APPROVED** [review]
Seems to work, thanks for your contribution!
